POST http://localhost:3000/user/users
Content-Type: application/json

{
    "firm_name": "Entreprise Admin",
    "first_name": "Admin",
    "last_name": "Admin",
    "email": "utilisateur@example.com",
    "phone_number": "123456789",
    "password": "1234",
    "has_mail": true,
    "is_admin": true
}

###

POST http://localhost:3000/user/users
Content-Type: application/json

{
    "firm_name": "Entreprise Morin",
    "first_name": "Marvin",
    "last_name": "Morin",
    "email": "marvin.morin@institutsolacroup.com",
    "phone_number": "0612980932",
    "password": "2486",
    "has_mail": true,
    "is_admin": false
}

###

POST http://localhost:3000/user/users
Content-Type: application/json

{
    "firm_name": "Entreprise 2",
    "first_name": "Prénom",
    "last_name": "Nom",
    "email": "utilisateur2@example.com",
    "phone_number": "123456789",
    "password": "1234",
    "has_mail": true,
    "is_admin": false
}

###

POST http://localhost:3000/user/users
Content-Type: application/json

{
    "firm_name": "Entreprise 3",
    "first_name": "Prénom",
    "last_name": "Nom",
    "email": "utilisateur3@example.com",
    "phone_number": "123456789",
    "password": "1234",
    "has_mail": true,
    "is_admin": false
}

###

POST http://localhost:3000/user/users
Content-Type: application/json

{
    "firm_name": "Entreprise 4",
    "first_name": "Prénom",
    "last_name": "Nom",
    "email": "utilisateur4@example.com",
    "phone_number": "123456789",
    "password": "motdepasse1234",
    "has_mail": true,
    "is_admin": false
}

###

POST http://localhost:3000/user/users
Content-Type: application/json

{
    "firm_name": "Institut Solacroup",
    "first_name": "Alex",
    "last_name": "Zicbel",
    "email": "alexandre.b@institutsolacroup.com",
    "phone_number": "123456789",
    "password": "1234",
    "has_mail": false,
    "is_admin": false
}

###
# Récupérer tous les utilisateurs
GET http://localhost:3000/user/users

###
# Récupérer un utilisateur par ID
GET http://localhost:3000/user/users/32

###
# Mettre à jour un utilisateur par ID
PUT http://localhost:3000/user/users/14
Content-Type: application/json

{
    "firm_name": "Morin",
    "first_name": "Marvin",
    "last_name": "Morin",
    "email": "marvin.morin@institutsolacroup.com",
    "phone_number": "0612980932",
    "password": "2486",
    "has_mail": false,
    "is_admin": false
}

###
# Supprimer un utilisateur par ID
DELETE http://localhost:3000/user/users/14
