# authUser - Authentification d'un utilisateur
POST http://localhost:3000/auth/connexion
Content-Type: application/json

{
  "firm_name": "Entreprise 1",
  "password": "1234"
}


###
POST http://localhost:3000/auth/connexion
Content-Type: application/json

{
  "firm_name": "Entreprise Admin",
  "password": "1234"
}

###
GET http://localhost:3000/auth/connecteduser

###
GET http://localhost:3000/auth/deconnexion



### FIRMNAME
GET http://localhost:3000/auth/firm_names

