
### request_mail.rest
# Méthode POST pour informer l'utilisateur qu'on a reçu du courrier au Bureau
POST http://localhost:3000/mail/received-mail/17
Content-Type: application/json

{}

###
# Méthode POST pour que l'utilisateur informe avoir récupéré son courrier
POST http://localhost:3000/mail/picked-up-mail/8
Content-Type: application/json

{}