POST http://localhost:3000/user/users

Content-Type: application/json

{
    "firm_name": "Nom de la société",
    "first_name": "Prénom",
    "last_name": "Nom",
    "email": "utilisateur@example.com",
    "phone_number": "123456789",
    "password": "motdepasse123",
    "last_received_mail": "2024-01-04T12:00:00Z",
    "last_picked_up": "2024-01-04T12:00:00Z",
    "has_mail": true,
    "is_admin": false
}