
### request_mail.rest

# POST pour que l'utilisateur informe de la récupération de son courrier
POST http://localhost:3000/mail/received-mail/22
Content-Type: application/json

{}

###
# POST pour que l'entreprise indique qu'il a réceptionné un courrier
POST http://localhost:3000/mail/picked-up-mail/22
Content-Type: application/json

{}